BC_ROUTES = "https://bctransit.doublemap.com/map/v2/routes"
BC_BUSES = "https://bctransit.doublemap.com/map/v2/buses"
BC_STOPS = "https://bctransit.doublemap.com/map/v2/stops"
OCCT_VEHICLES = "https://binghamtonupublic.etaspot.net/service.php?service=get_vehicles&token=TESTING"
OCCT_SERVICE_ANNOUNCEMENTS = "https://binghamtonupublic.etaspot.net/service.php?service=get_service_announcements&token=TESTING"
OCCT_ROUTES = "https://binghamtonupublic.etaspot.net/service.php?service=get_routes_announcements&token=TESTING"
